# Generated by Django 5.1.4 on 2025-01-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
