# Generated by Django 5.1.4 on 2025-01-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_data',
            name='email',
        ),
        migrations.AlterField(
            model_name='customer_data',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
