# Generated by Django 5.1.4 on 2025-04-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_orderdetails_date_orderdetails_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
