# Generated by Django 5.1.4 on 2025-04-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_rating',
        ),
        migrations.AddField(
            model_name='product',
            name='product_decription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
