# Generated by Django 5.1.4 on 2025-04-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
