# Generated by Django 5.1.4 on 2025-04-14 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_remove_product_quantity_alter_cart_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='product',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.cart'),
        ),
    ]
