# Generated by Django 5.1.4 on 2025-04-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_remove_orderdetails_product_orderdetails_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sub_total_amount',
            field=models.FloatField(default=0),
        ),
    ]
