# Generated by Django 5.1.4 on 2025-04-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_cart_sub_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='prnding', max_length=20),
        ),
    ]
