# Generated by Django 5.1.4 on 2025-04-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_remove_orderdetails_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='cart',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='carts',
            field=models.ManyToManyField(to='customer.cart'),
        ),
    ]
