# Generated by Django 5.1.4 on 2025-04-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_orderdetails_cart_orderdetails_carts'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
