# Generated by Django 5.1.4 on 2025-04-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_orderdetails_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='is_completed',
            new_name='is_finished',
        ),
        migrations.AddField(
            model_name='cart',
            name='is_finished',
            field=models.FloatField(default=False),
        ),
    ]
