# Generated by Django 5.1.4 on 2025-04-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_rename_is_completed_orderdetails_is_finished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
